events {}

http {
    upstream backends {
        server 10.7.25.240:3001;
        server 10.7.6.187:3002;
    }

    server {
        listen 443 ssl;
        server_name app.goodgoys.test;

        ssl_certificate "/Users/pushpendraaa/Desktop/cn-project 2/app.goodgoys.test.pem";
        ssl_certificate_key "/Users/pushpendraaa/Desktop/cn-project 2/app.goodgoys.test-key.pem";

        location / {
            proxy_pass http://backends;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}